name: Automated API tests using Newman CLI

on:
  push:
    paths:
      - "collections/**"
  workflow_dispatch:
    inputs:
      COLLECTION_ID:
        description: "Choose the ID of your collection"
        type: string
  schedule:
    - cron: "9 23 * * *"

jobs:
  automated-api-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Newman CLI
        run: npm install -g newman
      - name: Get the name of the collection in parameter
        id: collection
        run: |
          $COLLECTION_ID =  "${{ github.event.inputs.COLLECTION_ID }}"
          $COLLECTION_FILE = "collections/${COLLECTION_ID}.json"
          echo "::set-output name=collection_file::$COLLECTION_FILE"
          echo "::set-output name=collection_id::$COLLECTION_ID"
      - name: Run API tests
        run: |
          if ($env:GITHUB_EVENT_NAME -eq "workflow_dispatch") {
            $COLLECTION_FILE = "${{ steps.collection.outputs.collection_file }}"
            $COLLECTION_ID = "${{ steps.collection.outputs.collection_id }}"
            Write-Host "Collection file: $COLLECTION_FILE"
            newman run $COLLECTION_FILE -r htmlextra --reporter-htmlextra-export ./Reports/report_postman.html
          }
          elseif ($env:GITHUB_EVENT_NAME -eq "push" || ${{ github.event_name }} == 'schedule') {
            foreach ($file in Get-ChildItem collections/*.json) {
              newman run $file -r htmlextra --reporter-htmlextra-export ./Reports/report_postman.html
            }
          }
