name: Deploy via SSH

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Execute remote command via SSH
      env:
        JM_PASSWORD: ${{ secrets.JM_PASSWORD }}
      run: sshpass -p "$JM_PASSWORD" ssh -o StrictHostKeyChecking=no DELL@92.137.93.210 'ls'
